name: mod post images
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - run: pip install -r requirements.txt
      - shell: bash
        env:
          mod_api: ${{secrets.MOD_API}}
          nsfw_api: ${{secrets.NSFW_API}}
          report_api: ${{secrets.REPORT_API}}
        run: >
          python main.py --get-mod-api "$mod_api" --update-nsfw-api "$nsfw_api" --get-report-nsfw-api "$report_api"