name: gen not.db
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - run: pip install requests
      - shell: bash
        env:
          token: ${{ secrets.GH_PAT || github.token }}
          password: ${{ secrets.PASSWORD }}
        run: >
          python notdb.py --gh-token "$token" --password "$password"